//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZUS_Transport_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Applications
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        //[Required(ErrorMessage = "Введите шифр производственных затрат!")]
        public string CPC { get; set; }
        public Nullable<bool> IntercityСity { get; set; }
        //[Required(ErrorMessage = "Укажите цель использования транспорта!")]
        public string PurposeUsingTransport { get; set; }
        public Nullable<bool> Days { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int TypeCarID { get; set; }
        //[Required(ErrorMessage = "Укажите количество пассажиров!")]
        public Nullable<int> QuantityPassengers { get; set; }
        //[Required(ErrorMessage = "Укажите вес груза!")]
        public Nullable<double> CargoWeight { get; set; }
        public Nullable<int> CarID { get; set; }
        //[Required(ErrorMessage = "Укажите место подачи!")]
        public string PlaceSubmission { get; set; }
        //[Required(ErrorMessage = "Укажите маршрут!")]
        public string Route { get; set; }
        public string CommentClient { get; set; }
        public string СommentDirector { get; set; }
        public string СommentEconomist { get; set; }
        public string СommentDepartment { get; set; }
        public string СommentDispatcherNIIAR { get; set; }
        public string СommentDispatcherATA { get; set; }
        public int DirectorStatusDoneID { get; set; }
        public int EconomistStatusDoneID { get; set; }
        public int DepartmentStatusDoneID { get; set; }
        public int DispatcherNIIAR_StatusDoneID { get; set; }
        public int DispatcherATA_StatusDoneID { get; set; }
        public Nullable<bool> SelectionApplicationJoin { get; set; }
        public string ApplicationJoin { get; set; }

        public bool ArchiveApplications { get; set; } //архив заявок (checkBox)

        public virtual Cars Cars { get; set; }
        public virtual StatusesDone StatusesDone { get; set; }
        public virtual StatusesDone StatusesDone1 { get; set; }
        public virtual StatusesDone StatusesDone2 { get; set; }
        public virtual StatusesDone StatusesDone3 { get; set; }
        public virtual StatusesDone StatusesDone4 { get; set; }
        public virtual TypeCars TypeCars { get; set; }
        public virtual Users Users { get; set; }
    }
}
