//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZUS_Transport_Website.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Applications = new HashSet<Applications>();
        }

        public int Id { get; set; }
        public int TypeCarID { get; set; }
        public int ModelCarID { get; set; }
        public string RegisterSign { get; set; }
        public int StatusCarID { get; set; }
        public string ImageMimeType { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual ModelCars ModelCars { get; set; }
        public virtual StatusCars StatusCars { get; set; }
        public virtual TypeCars TypeCars { get; set; }
    }
}
