//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZUS_Transport_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Applications = new HashSet<Applications>();
        }
        public enum Status { Admin = 1, Client = 2, Director = 3, Economist = 4, DispatcherNIIAR = 5, Department = 6, DispatcherATA = 7 }
        [Key]
        public static int mode { get; set; } //Режим доступа
        public static int UserID { get; set; } // id зашедшего пользователя

        public int Id { get; set; }
        [Required(ErrorMessage = "Введите логин!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Введите пароль (8 символов)!")]
        //[RegularExpression("^(?=.*[0-9])(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*]")]
        //[RegularExpression("/(?=.*[A-Z].*)(?=.*[0-9].*)(?=.*[a-z].*)^[a-zA-z][a-zA-Z0-9]*[@!#+-]$")]
        //[RegularExpression("^(?=.*[0-9].*)^[0-9]*[0-9]$", ErrorMessage = "Пароль должен содержать хотя бы одну цифру!")]
        public string Password { get; set; }
        //[Compare("Password", ErrorMessage = "Пожалуйста, повторите пароль!")]
        //[EmailAddress(ErrorMessage = "Пожалуйста, введите корректный E-mail")]
        [Required(ErrorMessage = "Введите E-mail!")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Пожалуйста, введите корректный E-mail!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Введите фамилию!")]
        public string SurName { get; set; }
        [Required(ErrorMessage = "Введите имя!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Введите отчество!")]
        public string Partonymic { get; set; }
        [Required(ErrorMessage = "Введите должность!")]
        public string Post { get; set; }
        public int DivisionID { get; set; }
        [Required(ErrorMessage = "Введите номер комнаты!")]
        public int Room { get; set; }
        [Required(ErrorMessage = "Введите номер рабочего телефона!")]
        public string WorkPhone { get; set; }
        [Required(ErrorMessage = "Введите номер мобильного телефона!")]
        public string MobilePhone { get; set; }
        public int StatusID { get; set; }

        public bool remember { get; set; } //запомнить пользователя (checkBox)

        public System.Web.Mvc.SelectList Divisions_ { get; set; }
        public System.Web.Mvc.SelectList Building { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual Divisions Divisions { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
